#!/bin/bash
# move me to /etc/network/if-up.d/

if [ $IFACE = "enp1s0" ]
then
	sleep 5
	# 10.10.150.0/24
	sudo ip route add 10.10.150.0/24 via 200.200.200.1 dev enp1s0
fi

if [ $IFACE = "enp7s0" ]
then
	sleep 5
	# buildings
	sudo ip route add 200.200.202.0/30 via 200.200.201.2 dev enp7s0
	sudo ip route add 200.200.204.0/30 via 200.200.201.2 dev enp7s0
	# 10.10.152.0/24
	sudo ip route add 10.10.152.0/24 via 200.200.201.2 dev enp7s0
	# 10.10.153.0/24
	sudo ip route add 10.10.153.0/24 via 200.200.201.2 dev enp7s0
	# 10.10.154.0/24
	sudo ip route add 10.10.154.0/24 via 200.200.201.2 dev enp7s0
fi

if [ $IFACE = "enp8s0" ]
then
	sleep 5
	sudo iptables -F
	sleep 0.5
	# clientes que salen
	sudo iptables -A FORWARD -i enp8s0 -s 10.10.151.5 -d 10.10.150.2 -j ACCEPT
	sudo iptables -A FORWARD -i enp8s0 -s 10.10.151.5 -d 10.10.150.3 -j ACCEPT
	sudo iptables -A FORWARD -i enp8s0 -s 10.10.151.5 -d 10.10.150.4 -j ACCEPT
	sudo iptables -A FORWARD -i enp8s0 -s 10.10.151.6 -d 10.10.150.2 -j ACCEPT
	sudo iptables -A FORWARD -i enp8s0 -s 10.10.151.6 -d 10.10.150.3 -j ACCEPT
	sudo iptables -A FORWARD -i enp8s0 -s 10.10.151.6 -d 10.10.150.4 -j ACCEPT
	sudo iptables -A FORWARD -i enp8s0 -s 10.10.151.6 -d 10.10.153.12 -j ACCEPT
	sudo iptables -A FORWARD -i enp8s0 -s 10.10.151.6 -d 10.10.153.13 -j ACCEPT
	sleep 0.5
	# related, established
	# E
	sudo iptables -A FORWARD -i enp8s0 -s 10.10.151.18 -d 10.10.153.12 -m state --state ESTABLISHED,RELATED -j ACCEPT
	sudo iptables -A FORWARD -i enp8s0 -s 10.10.151.18 -d 10.10.153.14 -m state --state ESTABLISHED,RELATED -j ACCEPT
	sleep 0.5
	# reject
	sudo iptables -A FORWARD -i enp8s0 -j REJECT
	sleep 0.5
fi
