#!/bin/bash
# move me to /etc/network/if-up.d/

if [ $IFACE = "enp1s0" ]
then
	sleep 5
	# routes with other buildings
	sudo ip route add 200.200.201.0/30 via 200.200.200.2 dev enp1s0
	sudo ip route add 200.200.202.0/30 via 200.200.200.2 dev enp1s0
	sudo ip route add 200.200.204.0/30 via 200.200.200.2 dev enp1s0

	# 10.10.150.0/24
	# 10.10.151.0/24
	sudo ip route add 10.10.151.0/24 via 200.200.200.2 dev enp1s0
	# 10.10.152.0/24
	sudo ip route add 10.10.152.0/24 via 200.200.200.2 dev enp1s0
	# 10.10.153.0/24
	sudo ip route add 10.10.153.0/24 via 200.200.200.2 dev enp1s0
	# 10.10.154.0/24
	sudo ip route add 10.10.154.0/24 via 200.200.200.2 dev enp1s0
fi

if [ $IFACE = "enp7s0" ]
then
	sleep 5
	sudo iptables -F
	sleep 0.5
	# clientes que salen
	sudo iptables -A FORWARD -i enp7s0 -s 10.10.150.2 -d 10.10.151.5 -j ACCEPT
	sudo iptables -A FORWARD -i enp7s0 -s 10.10.150.3 -d 10.10.151.5 -j ACCEPT
	sudo iptables -A FORWARD -i enp7s0 -s 10.10.150.4 -d 10.10.151.5 -j ACCEPT
	sudo iptables -A FORWARD -i enp7s0 -s 10.10.150.2 -d 10.10.153.12 -j ACCEPT
	sudo iptables -A FORWARD -i enp7s0 -s 10.10.150.3 -d 10.10.153.12 -j ACCEPT
	sudo iptables -A FORWARD -i enp7s0 -s 10.10.150.4 -d 10.10.153.12 -j ACCEPT
	sudo iptables -A FORWARD -i enp7s0 -s 10.10.150.2 -d 10.10.153.13 -j ACCEPT
	sudo iptables -A FORWARD -i enp7s0 -s 10.10.150.3 -d 10.10.153.13 -j ACCEPT
	sudo iptables -A FORWARD -i enp7s0 -s 10.10.150.4 -d 10.10.153.13 -j ACCEPT
	sleep 0.5
	# related, established
	# B
	sudo iptables -A FORWARD -i enp7s0 -s 10.10.150.2 -d 10.10.151.6 -m state --state ESTABLISHED,RELATED -j ACCEPT
	sudo iptables -A FORWARD -i enp7s0 -s 10.10.150.3 -d 10.10.151.6 -m state --state ESTABLISHED,RELATED -j ACCEPT
	sudo iptables -A FORWARD -i enp7s0 -s 10.10.150.4 -d 10.10.151.6 -m state --state ESTABLISHED,RELATED -j ACCEPT
	sleep 0.5
	# E
	sudo iptables -A FORWARD -i enp7s0 -s 10.10.150.2 -d 10.10.153.14 -m state --state ESTABLISHED,RELATED -j ACCEPT
	sleep 0.5
	sudo iptables -A FORWARD -i enp7s0 -j REJECT
	sleep 0.5
fi
